/* Automatisch generiert von /bump — nicht manuell bearbeiten. */
#ifndef ESP32_GRILLTHERMO_VERSION_H
#define ESP32_GRILLTHERMO_VERSION_H

#define ESP32_GRILLTHERMO_VERSION_MAJOR (1)
#define ESP32_GRILLTHERMO_VERSION_MINOR (0)
#define ESP32_GRILLTHERMO_VERSION_STRING "1.0"

#endif /* ESP32_GRILLTHERMO_VERSION_H */
